// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sensors.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Main message wrapper - contains one of many sensor types
struct Arvos_SensorMessage: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var timestampNs: UInt64 {
    get {return _storage._timestampNs}
    set {_uniqueStorage()._timestampNs = newValue}
  }

  var data: OneOf_Data? {
    get {return _storage._data}
    set {_uniqueStorage()._data = newValue}
  }

  var handshake: Arvos_HandshakeData {
    get {
      if case .handshake(let v)? = _storage._data {return v}
      return Arvos_HandshakeData()
    }
    set {_uniqueStorage()._data = .handshake(newValue)}
  }

  var imu: Arvos_IMUData {
    get {
      if case .imu(let v)? = _storage._data {return v}
      return Arvos_IMUData()
    }
    set {_uniqueStorage()._data = .imu(newValue)}
  }

  var gps: Arvos_GPSData {
    get {
      if case .gps(let v)? = _storage._data {return v}
      return Arvos_GPSData()
    }
    set {_uniqueStorage()._data = .gps(newValue)}
  }

  var pose: Arvos_PoseData {
    get {
      if case .pose(let v)? = _storage._data {return v}
      return Arvos_PoseData()
    }
    set {_uniqueStorage()._data = .pose(newValue)}
  }

  var cameraMetadata: Arvos_CameraFrameMetadata {
    get {
      if case .cameraMetadata(let v)? = _storage._data {return v}
      return Arvos_CameraFrameMetadata()
    }
    set {_uniqueStorage()._data = .cameraMetadata(newValue)}
  }

  var depthMetadata: Arvos_DepthFrameMetadata {
    get {
      if case .depthMetadata(let v)? = _storage._data {return v}
      return Arvos_DepthFrameMetadata()
    }
    set {_uniqueStorage()._data = .depthMetadata(newValue)}
  }

  var watchImu: Arvos_WatchIMUData {
    get {
      if case .watchImu(let v)? = _storage._data {return v}
      return Arvos_WatchIMUData()
    }
    set {_uniqueStorage()._data = .watchImu(newValue)}
  }

  var watchAttitude: Arvos_WatchAttitudeData {
    get {
      if case .watchAttitude(let v)? = _storage._data {return v}
      return Arvos_WatchAttitudeData()
    }
    set {_uniqueStorage()._data = .watchAttitude(newValue)}
  }

  var watchActivity: Arvos_WatchMotionActivityData {
    get {
      if case .watchActivity(let v)? = _storage._data {return v}
      return Arvos_WatchMotionActivityData()
    }
    set {_uniqueStorage()._data = .watchActivity(newValue)}
  }

  var status: Arvos_StatusData {
    get {
      if case .status(let v)? = _storage._data {return v}
      return Arvos_StatusData()
    }
    set {_uniqueStorage()._data = .status(newValue)}
  }

  var error: Arvos_ErrorData {
    get {
      if case .error(let v)? = _storage._data {return v}
      return Arvos_ErrorData()
    }
    set {_uniqueStorage()._data = .error(newValue)}
  }

  /// Optional: Binary data follows (for camera/depth frames)
  var binaryData: Data {
    get {return _storage._binaryData}
    set {_uniqueStorage()._binaryData = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Data: Equatable, Sendable {
    case handshake(Arvos_HandshakeData)
    case imu(Arvos_IMUData)
    case gps(Arvos_GPSData)
    case pose(Arvos_PoseData)
    case cameraMetadata(Arvos_CameraFrameMetadata)
    case depthMetadata(Arvos_DepthFrameMetadata)
    case watchImu(Arvos_WatchIMUData)
    case watchAttitude(Arvos_WatchAttitudeData)
    case watchActivity(Arvos_WatchMotionActivityData)
    case status(Arvos_StatusData)
    case error(Arvos_ErrorData)

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Control messages from server to iPhone
struct Arvos_ControlMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var timestampNs: UInt64 = 0

  var command: Arvos_ControlMessage.OneOf_Command? = nil

  var startRecording: Arvos_StartRecordingCommand {
    get {
      if case .startRecording(let v)? = command {return v}
      return Arvos_StartRecordingCommand()
    }
    set {command = .startRecording(newValue)}
  }

  var stopRecording: Arvos_StopRecordingCommand {
    get {
      if case .stopRecording(let v)? = command {return v}
      return Arvos_StopRecordingCommand()
    }
    set {command = .stopRecording(newValue)}
  }

  var changeMode: Arvos_ChangeModeCommand {
    get {
      if case .changeMode(let v)? = command {return v}
      return Arvos_ChangeModeCommand()
    }
    set {command = .changeMode(newValue)}
  }

  var ack: Arvos_AcknowledgmentCommand {
    get {
      if case .ack(let v)? = command {return v}
      return Arvos_AcknowledgmentCommand()
    }
    set {command = .ack(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Command: Equatable, Sendable {
    case startRecording(Arvos_StartRecordingCommand)
    case stopRecording(Arvos_StopRecordingCommand)
    case changeMode(Arvos_ChangeModeCommand)
    case ack(Arvos_AcknowledgmentCommand)

  }

  init() {}
}

struct Arvos_HandshakeData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var deviceName: String = String()

  var deviceModel: String = String()

  var osVersion: String = String()

  var appVersion: String = String()

  var capabilities: Arvos_DeviceCapabilities {
    get {return _capabilities ?? Arvos_DeviceCapabilities()}
    set {_capabilities = newValue}
  }
  /// Returns true if `capabilities` has been explicitly set.
  var hasCapabilities: Bool {return self._capabilities != nil}
  /// Clears the value of `capabilities`. Subsequent reads from it will return its default value.
  mutating func clearCapabilities() {self._capabilities = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _capabilities: Arvos_DeviceCapabilities? = nil
}

struct Arvos_DeviceCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var hasLidar_p: Bool = false

  var hasArkit_p: Bool = false

  var hasGps_p: Bool = false

  var hasImu_p: Bool = false

  var hasWatch_p: Bool = false

  var supportedModes: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_IMUData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// rad/s
  var angularVelocity: Arvos_Vector3 {
    get {return _angularVelocity ?? Arvos_Vector3()}
    set {_angularVelocity = newValue}
  }
  /// Returns true if `angularVelocity` has been explicitly set.
  var hasAngularVelocity: Bool {return self._angularVelocity != nil}
  /// Clears the value of `angularVelocity`. Subsequent reads from it will return its default value.
  mutating func clearAngularVelocity() {self._angularVelocity = nil}

  /// m/s²
  var linearAcceleration: Arvos_Vector3 {
    get {return _linearAcceleration ?? Arvos_Vector3()}
    set {_linearAcceleration = newValue}
  }
  /// Returns true if `linearAcceleration` has been explicitly set.
  var hasLinearAcceleration: Bool {return self._linearAcceleration != nil}
  /// Clears the value of `linearAcceleration`. Subsequent reads from it will return its default value.
  mutating func clearLinearAcceleration() {self._linearAcceleration = nil}

  /// μT (optional)
  var magneticField: Arvos_Vector3 {
    get {return _magneticField ?? Arvos_Vector3()}
    set {_magneticField = newValue}
  }
  /// Returns true if `magneticField` has been explicitly set.
  var hasMagneticField: Bool {return self._magneticField != nil}
  /// Clears the value of `magneticField`. Subsequent reads from it will return its default value.
  mutating func clearMagneticField() {self._magneticField = nil}

  /// m/s² (optional)
  var gravity: Arvos_Vector3 {
    get {return _gravity ?? Arvos_Vector3()}
    set {_gravity = newValue}
  }
  /// Returns true if `gravity` has been explicitly set.
  var hasGravity: Bool {return self._gravity != nil}
  /// Clears the value of `gravity`. Subsequent reads from it will return its default value.
  mutating func clearGravity() {self._gravity = nil}

  /// roll, pitch, yaw in radians (optional)
  var attitude: Arvos_Vector3 {
    get {return _attitude ?? Arvos_Vector3()}
    set {_attitude = newValue}
  }
  /// Returns true if `attitude` has been explicitly set.
  var hasAttitude: Bool {return self._attitude != nil}
  /// Clears the value of `attitude`. Subsequent reads from it will return its default value.
  mutating func clearAttitude() {self._attitude = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _angularVelocity: Arvos_Vector3? = nil
  fileprivate var _linearAcceleration: Arvos_Vector3? = nil
  fileprivate var _magneticField: Arvos_Vector3? = nil
  fileprivate var _gravity: Arvos_Vector3? = nil
  fileprivate var _attitude: Arvos_Vector3? = nil
}

struct Arvos_GPSData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// degrees
  var latitude: Double = 0

  /// degrees
  var longitude: Double = 0

  /// meters
  var altitude: Double = 0

  /// meters
  var horizontalAccuracy: Double = 0

  /// meters
  var verticalAccuracy: Double = 0

  /// m/s
  var speed: Double = 0

  /// degrees
  var course: Double = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_PoseData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// meters (x, y, z)
  var position: Arvos_Vector3 {
    get {return _position ?? Arvos_Vector3()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  var hasPosition: Bool {return self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  mutating func clearPosition() {self._position = nil}

  /// quaternion (x, y, z, w)
  var orientation: Arvos_Quaternion {
    get {return _orientation ?? Arvos_Quaternion()}
    set {_orientation = newValue}
  }
  /// Returns true if `orientation` has been explicitly set.
  var hasOrientation: Bool {return self._orientation != nil}
  /// Clears the value of `orientation`. Subsequent reads from it will return its default value.
  mutating func clearOrientation() {self._orientation = nil}

  /// "normal", "limited_*", "not_available"
  var trackingState: String = String()

  /// optional 4x4 transform matrix
  var transform: Arvos_Matrix4x4 {
    get {return _transform ?? Arvos_Matrix4x4()}
    set {_transform = newValue}
  }
  /// Returns true if `transform` has been explicitly set.
  var hasTransform: Bool {return self._transform != nil}
  /// Clears the value of `transform`. Subsequent reads from it will return its default value.
  mutating func clearTransform() {self._transform = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _position: Arvos_Vector3? = nil
  fileprivate var _orientation: Arvos_Quaternion? = nil
  fileprivate var _transform: Arvos_Matrix4x4? = nil
}

struct Arvos_CameraFrameMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var width: UInt32 = 0

  var height: UInt32 = 0

  /// "jpeg", "h264", "png"
  var format: String = String()

  var compressedSize: UInt32 = 0

  /// optional
  var intrinsics: Arvos_CameraIntrinsics {
    get {return _intrinsics ?? Arvos_CameraIntrinsics()}
    set {_intrinsics = newValue}
  }
  /// Returns true if `intrinsics` has been explicitly set.
  var hasIntrinsics: Bool {return self._intrinsics != nil}
  /// Clears the value of `intrinsics`. Subsequent reads from it will return its default value.
  mutating func clearIntrinsics() {self._intrinsics = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _intrinsics: Arvos_CameraIntrinsics? = nil
}

struct Arvos_DepthFrameMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pointCount: UInt32 = 0

  /// meters
  var minDepth: Float = 0

  /// meters
  var maxDepth: Float = 0

  /// "ply", "raw_depth"
  var format: String = String()

  var dataSize: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_WatchIMUData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// rad/s
  var angularVelocity: Arvos_Vector3 {
    get {return _angularVelocity ?? Arvos_Vector3()}
    set {_angularVelocity = newValue}
  }
  /// Returns true if `angularVelocity` has been explicitly set.
  var hasAngularVelocity: Bool {return self._angularVelocity != nil}
  /// Clears the value of `angularVelocity`. Subsequent reads from it will return its default value.
  mutating func clearAngularVelocity() {self._angularVelocity = nil}

  /// m/s²
  var linearAcceleration: Arvos_Vector3 {
    get {return _linearAcceleration ?? Arvos_Vector3()}
    set {_linearAcceleration = newValue}
  }
  /// Returns true if `linearAcceleration` has been explicitly set.
  var hasLinearAcceleration: Bool {return self._linearAcceleration != nil}
  /// Clears the value of `linearAcceleration`. Subsequent reads from it will return its default value.
  mutating func clearLinearAcceleration() {self._linearAcceleration = nil}

  /// m/s²
  var gravity: Arvos_Vector3 {
    get {return _gravity ?? Arvos_Vector3()}
    set {_gravity = newValue}
  }
  /// Returns true if `gravity` has been explicitly set.
  var hasGravity: Bool {return self._gravity != nil}
  /// Clears the value of `gravity`. Subsequent reads from it will return its default value.
  mutating func clearGravity() {self._gravity = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _angularVelocity: Arvos_Vector3? = nil
  fileprivate var _linearAcceleration: Arvos_Vector3? = nil
  fileprivate var _gravity: Arvos_Vector3? = nil
}

struct Arvos_WatchAttitudeData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// x, y, z, w
  var quaternion: Arvos_Quaternion {
    get {return _quaternion ?? Arvos_Quaternion()}
    set {_quaternion = newValue}
  }
  /// Returns true if `quaternion` has been explicitly set.
  var hasQuaternion: Bool {return self._quaternion != nil}
  /// Clears the value of `quaternion`. Subsequent reads from it will return its default value.
  mutating func clearQuaternion() {self._quaternion = nil}

  /// radians
  var pitch: Float = 0

  /// radians
  var roll: Float = 0

  /// radians
  var yaw: Float = 0

  /// "xArbitraryZVertical", "xArbitraryCorrectedZVertical", etc.
  var referenceFrame: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _quaternion: Arvos_Quaternion? = nil
}

struct Arvos_WatchMotionActivityData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "walking", "running", "cycling", "vehicle", "stationary", "unknown"
  var state: String = String()

  /// 0.0 - 1.0
  var confidence: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_StatusData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "connected", "streaming", "recording", "stopped", "error"
  var status: String = String()

  /// optional message
  var message: String = String()

  /// optional session ID
  var sessionID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_ErrorData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var error: String = String()

  /// optional details
  var details: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_StartRecordingCommand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// optional session ID
  var sessionID: String = String()

  /// optional mode
  var mode: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_StopRecordingCommand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// optional session ID
  var sessionID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_ChangeModeCommand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "Mapping", "Full Sensor", etc.
  var mode: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_AcknowledgmentCommand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ID of acknowledged message
  var messageID: String = String()

  var success: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_Vector3: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var x: Float = 0

  var y: Float = 0

  var z: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_Quaternion: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var x: Float = 0

  var y: Float = 0

  var z: Float = 0

  var w: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_Matrix4x4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 16 values in column-major order
  var values: [Float] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Arvos_CameraIntrinsics: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// focal length x
  var fx: Float = 0

  /// focal length y
  var fy: Float = 0

  /// principal point x
  var cx: Float = 0

  /// principal point y
  var cy: Float = 0

  /// distortion coefficients (k1, k2, p1, p2, k3...)
  var distortion: [Float] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "arvos"

extension Arvos_SensorMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SensorMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ns\0\u{2}\u{9}handshake\0\u{1}imu\0\u{1}gps\0\u{1}pose\0\u{3}camera_metadata\0\u{3}depth_metadata\0\u{3}watch_imu\0\u{3}watch_attitude\0\u{3}watch_activity\0\u{1}status\0\u{1}error\0\u{4}P\u{1}binary_data\0")

  fileprivate class _StorageClass {
    var _timestampNs: UInt64 = 0
    var _data: Arvos_SensorMessage.OneOf_Data?
    var _binaryData: Data = Data()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _timestampNs = source._timestampNs
      _data = source._data
      _binaryData = source._binaryData
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._timestampNs) }()
        case 10: try {
          var v: Arvos_HandshakeData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .handshake(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .handshake(v)
          }
        }()
        case 11: try {
          var v: Arvos_IMUData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .imu(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .imu(v)
          }
        }()
        case 12: try {
          var v: Arvos_GPSData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .gps(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .gps(v)
          }
        }()
        case 13: try {
          var v: Arvos_PoseData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .pose(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .pose(v)
          }
        }()
        case 14: try {
          var v: Arvos_CameraFrameMetadata?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .cameraMetadata(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .cameraMetadata(v)
          }
        }()
        case 15: try {
          var v: Arvos_DepthFrameMetadata?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .depthMetadata(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .depthMetadata(v)
          }
        }()
        case 16: try {
          var v: Arvos_WatchIMUData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .watchImu(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .watchImu(v)
          }
        }()
        case 17: try {
          var v: Arvos_WatchAttitudeData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .watchAttitude(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .watchAttitude(v)
          }
        }()
        case 18: try {
          var v: Arvos_WatchMotionActivityData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .watchActivity(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .watchActivity(v)
          }
        }()
        case 19: try {
          var v: Arvos_StatusData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .status(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .status(v)
          }
        }()
        case 20: try {
          var v: Arvos_ErrorData?
          var hadOneofValue = false
          if let current = _storage._data {
            hadOneofValue = true
            if case .error(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._data = .error(v)
          }
        }()
        case 100: try { try decoder.decodeSingularBytesField(value: &_storage._binaryData) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._timestampNs != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._timestampNs, fieldNumber: 1)
      }
      switch _storage._data {
      case .handshake?: try {
        guard case .handshake(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      }()
      case .imu?: try {
        guard case .imu(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      }()
      case .gps?: try {
        guard case .gps(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }()
      case .pose?: try {
        guard case .pose(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      }()
      case .cameraMetadata?: try {
        guard case .cameraMetadata(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      }()
      case .depthMetadata?: try {
        guard case .depthMetadata(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      }()
      case .watchImu?: try {
        guard case .watchImu(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      }()
      case .watchAttitude?: try {
        guard case .watchAttitude(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      }()
      case .watchActivity?: try {
        guard case .watchActivity(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      }()
      case .status?: try {
        guard case .status(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 19)
      }()
      case .error?: try {
        guard case .error(let v)? = _storage._data else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      }()
      case nil: break
      }
      if !_storage._binaryData.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._binaryData, fieldNumber: 100)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_SensorMessage, rhs: Arvos_SensorMessage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._timestampNs != rhs_storage._timestampNs {return false}
        if _storage._data != rhs_storage._data {return false}
        if _storage._binaryData != rhs_storage._binaryData {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_ControlMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ControlMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ns\0\u{4}\u{9}start_recording\0\u{3}stop_recording\0\u{3}change_mode\0\u{1}ack\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.timestampNs) }()
      case 10: try {
        var v: Arvos_StartRecordingCommand?
        var hadOneofValue = false
        if let current = self.command {
          hadOneofValue = true
          if case .startRecording(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.command = .startRecording(v)
        }
      }()
      case 11: try {
        var v: Arvos_StopRecordingCommand?
        var hadOneofValue = false
        if let current = self.command {
          hadOneofValue = true
          if case .stopRecording(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.command = .stopRecording(v)
        }
      }()
      case 12: try {
        var v: Arvos_ChangeModeCommand?
        var hadOneofValue = false
        if let current = self.command {
          hadOneofValue = true
          if case .changeMode(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.command = .changeMode(v)
        }
      }()
      case 13: try {
        var v: Arvos_AcknowledgmentCommand?
        var hadOneofValue = false
        if let current = self.command {
          hadOneofValue = true
          if case .ack(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.command = .ack(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.timestampNs != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestampNs, fieldNumber: 1)
    }
    switch self.command {
    case .startRecording?: try {
      guard case .startRecording(let v)? = self.command else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .stopRecording?: try {
      guard case .stopRecording(let v)? = self.command else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .changeMode?: try {
      guard case .changeMode(let v)? = self.command else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .ack?: try {
      guard case .ack(let v)? = self.command else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_ControlMessage, rhs: Arvos_ControlMessage) -> Bool {
    if lhs.timestampNs != rhs.timestampNs {return false}
    if lhs.command != rhs.command {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_HandshakeData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HandshakeData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_name\0\u{3}device_model\0\u{3}os_version\0\u{3}app_version\0\u{1}capabilities\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.deviceName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceModel) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.osVersion) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.appVersion) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._capabilities) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.deviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceName, fieldNumber: 1)
    }
    if !self.deviceModel.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceModel, fieldNumber: 2)
    }
    if !self.osVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.osVersion, fieldNumber: 3)
    }
    if !self.appVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.appVersion, fieldNumber: 4)
    }
    try { if let v = self._capabilities {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_HandshakeData, rhs: Arvos_HandshakeData) -> Bool {
    if lhs.deviceName != rhs.deviceName {return false}
    if lhs.deviceModel != rhs.deviceModel {return false}
    if lhs.osVersion != rhs.osVersion {return false}
    if lhs.appVersion != rhs.appVersion {return false}
    if lhs._capabilities != rhs._capabilities {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_DeviceCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceCapabilities"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}has_lidar\0\u{3}has_arkit\0\u{3}has_gps\0\u{3}has_imu\0\u{3}has_watch\0\u{3}supported_modes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.hasLidar_p) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.hasArkit_p) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.hasGps_p) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.hasImu_p) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.hasWatch_p) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.supportedModes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.hasLidar_p != false {
      try visitor.visitSingularBoolField(value: self.hasLidar_p, fieldNumber: 1)
    }
    if self.hasArkit_p != false {
      try visitor.visitSingularBoolField(value: self.hasArkit_p, fieldNumber: 2)
    }
    if self.hasGps_p != false {
      try visitor.visitSingularBoolField(value: self.hasGps_p, fieldNumber: 3)
    }
    if self.hasImu_p != false {
      try visitor.visitSingularBoolField(value: self.hasImu_p, fieldNumber: 4)
    }
    if self.hasWatch_p != false {
      try visitor.visitSingularBoolField(value: self.hasWatch_p, fieldNumber: 5)
    }
    if !self.supportedModes.isEmpty {
      try visitor.visitRepeatedStringField(value: self.supportedModes, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_DeviceCapabilities, rhs: Arvos_DeviceCapabilities) -> Bool {
    if lhs.hasLidar_p != rhs.hasLidar_p {return false}
    if lhs.hasArkit_p != rhs.hasArkit_p {return false}
    if lhs.hasGps_p != rhs.hasGps_p {return false}
    if lhs.hasImu_p != rhs.hasImu_p {return false}
    if lhs.hasWatch_p != rhs.hasWatch_p {return false}
    if lhs.supportedModes != rhs.supportedModes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_IMUData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".IMUData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}angular_velocity\0\u{3}linear_acceleration\0\u{3}magnetic_field\0\u{1}gravity\0\u{1}attitude\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._angularVelocity) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._linearAcceleration) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._magneticField) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._gravity) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._attitude) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._angularVelocity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._linearAcceleration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._magneticField {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._gravity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._attitude {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_IMUData, rhs: Arvos_IMUData) -> Bool {
    if lhs._angularVelocity != rhs._angularVelocity {return false}
    if lhs._linearAcceleration != rhs._linearAcceleration {return false}
    if lhs._magneticField != rhs._magneticField {return false}
    if lhs._gravity != rhs._gravity {return false}
    if lhs._attitude != rhs._attitude {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_GPSData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GPSData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}latitude\0\u{1}longitude\0\u{1}altitude\0\u{3}horizontal_accuracy\0\u{3}vertical_accuracy\0\u{1}speed\0\u{1}course\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.latitude) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.longitude) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.altitude) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.horizontalAccuracy) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.verticalAccuracy) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.speed) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.course) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.latitude.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.latitude, fieldNumber: 1)
    }
    if self.longitude.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.longitude, fieldNumber: 2)
    }
    if self.altitude.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.altitude, fieldNumber: 3)
    }
    if self.horizontalAccuracy.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.horizontalAccuracy, fieldNumber: 4)
    }
    if self.verticalAccuracy.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.verticalAccuracy, fieldNumber: 5)
    }
    if self.speed.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.speed, fieldNumber: 6)
    }
    if self.course.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.course, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_GPSData, rhs: Arvos_GPSData) -> Bool {
    if lhs.latitude != rhs.latitude {return false}
    if lhs.longitude != rhs.longitude {return false}
    if lhs.altitude != rhs.altitude {return false}
    if lhs.horizontalAccuracy != rhs.horizontalAccuracy {return false}
    if lhs.verticalAccuracy != rhs.verticalAccuracy {return false}
    if lhs.speed != rhs.speed {return false}
    if lhs.course != rhs.course {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_PoseData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PoseData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{1}orientation\0\u{3}tracking_state\0\u{1}transform\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._orientation) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.trackingState) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._transform) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._orientation {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.trackingState.isEmpty {
      try visitor.visitSingularStringField(value: self.trackingState, fieldNumber: 3)
    }
    try { if let v = self._transform {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_PoseData, rhs: Arvos_PoseData) -> Bool {
    if lhs._position != rhs._position {return false}
    if lhs._orientation != rhs._orientation {return false}
    if lhs.trackingState != rhs.trackingState {return false}
    if lhs._transform != rhs._transform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_CameraFrameMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CameraFrameMetadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}width\0\u{1}height\0\u{1}format\0\u{3}compressed_size\0\u{1}intrinsics\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.format) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.compressedSize) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._intrinsics) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 2)
    }
    if !self.format.isEmpty {
      try visitor.visitSingularStringField(value: self.format, fieldNumber: 3)
    }
    if self.compressedSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.compressedSize, fieldNumber: 4)
    }
    try { if let v = self._intrinsics {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_CameraFrameMetadata, rhs: Arvos_CameraFrameMetadata) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.format != rhs.format {return false}
    if lhs.compressedSize != rhs.compressedSize {return false}
    if lhs._intrinsics != rhs._intrinsics {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_DepthFrameMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DepthFrameMetadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}point_count\0\u{3}min_depth\0\u{3}max_depth\0\u{1}format\0\u{3}data_size\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.pointCount) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.minDepth) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.maxDepth) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.format) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.dataSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pointCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.pointCount, fieldNumber: 1)
    }
    if self.minDepth.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.minDepth, fieldNumber: 2)
    }
    if self.maxDepth.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.maxDepth, fieldNumber: 3)
    }
    if !self.format.isEmpty {
      try visitor.visitSingularStringField(value: self.format, fieldNumber: 4)
    }
    if self.dataSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.dataSize, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_DepthFrameMetadata, rhs: Arvos_DepthFrameMetadata) -> Bool {
    if lhs.pointCount != rhs.pointCount {return false}
    if lhs.minDepth != rhs.minDepth {return false}
    if lhs.maxDepth != rhs.maxDepth {return false}
    if lhs.format != rhs.format {return false}
    if lhs.dataSize != rhs.dataSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_WatchIMUData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WatchIMUData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}angular_velocity\0\u{3}linear_acceleration\0\u{1}gravity\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._angularVelocity) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._linearAcceleration) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._gravity) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._angularVelocity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._linearAcceleration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._gravity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_WatchIMUData, rhs: Arvos_WatchIMUData) -> Bool {
    if lhs._angularVelocity != rhs._angularVelocity {return false}
    if lhs._linearAcceleration != rhs._linearAcceleration {return false}
    if lhs._gravity != rhs._gravity {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_WatchAttitudeData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WatchAttitudeData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}quaternion\0\u{1}pitch\0\u{1}roll\0\u{1}yaw\0\u{3}reference_frame\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._quaternion) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.pitch) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.roll) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.yaw) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.referenceFrame) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._quaternion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.pitch.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pitch, fieldNumber: 2)
    }
    if self.roll.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.roll, fieldNumber: 3)
    }
    if self.yaw.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.yaw, fieldNumber: 4)
    }
    if !self.referenceFrame.isEmpty {
      try visitor.visitSingularStringField(value: self.referenceFrame, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_WatchAttitudeData, rhs: Arvos_WatchAttitudeData) -> Bool {
    if lhs._quaternion != rhs._quaternion {return false}
    if lhs.pitch != rhs.pitch {return false}
    if lhs.roll != rhs.roll {return false}
    if lhs.yaw != rhs.yaw {return false}
    if lhs.referenceFrame != rhs.referenceFrame {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_WatchMotionActivityData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WatchMotionActivityData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}state\0\u{1}confidence\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 1)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_WatchMotionActivityData, rhs: Arvos_WatchMotionActivityData) -> Bool {
    if lhs.state != rhs.state {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_StatusData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StatusData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}message\0\u{3}session_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_StatusData, rhs: Arvos_StatusData) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.message != rhs.message {return false}
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_ErrorData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ErrorData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0\u{1}details\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.error) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.details) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.error.isEmpty {
      try visitor.visitSingularStringField(value: self.error, fieldNumber: 1)
    }
    if !self.details.isEmpty {
      try visitor.visitSingularStringField(value: self.details, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_ErrorData, rhs: Arvos_ErrorData) -> Bool {
    if lhs.error != rhs.error {return false}
    if lhs.details != rhs.details {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_StartRecordingCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StartRecordingCommand"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{1}mode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 1)
    }
    if !self.mode.isEmpty {
      try visitor.visitSingularStringField(value: self.mode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_StartRecordingCommand, rhs: Arvos_StartRecordingCommand) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_StopRecordingCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".StopRecordingCommand"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_StopRecordingCommand, rhs: Arvos_StopRecordingCommand) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_ChangeModeCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChangeModeCommand"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mode.isEmpty {
      try visitor.visitSingularStringField(value: self.mode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_ChangeModeCommand, rhs: Arvos_ChangeModeCommand) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_AcknowledgmentCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AcknowledgmentCommand"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_id\0\u{1}success\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.messageID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messageID.isEmpty {
      try visitor.visitSingularStringField(value: self.messageID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_AcknowledgmentCommand, rhs: Arvos_AcknowledgmentCommand) -> Bool {
    if lhs.messageID != rhs.messageID {return false}
    if lhs.success != rhs.success {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_Vector3: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Vector3"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}z\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.z) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    if self.z.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.z, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_Vector3, rhs: Arvos_Vector3) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.z != rhs.z {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_Quaternion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Quaternion"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0\u{1}z\0\u{1}w\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.z) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.w) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    if self.z.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.z, fieldNumber: 3)
    }
    if self.w.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.w, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_Quaternion, rhs: Arvos_Quaternion) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.z != rhs.z {return false}
    if lhs.w != rhs.w {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_Matrix4x4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Matrix4x4"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}values\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedFloatField(value: &self.values) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitPackedFloatField(value: self.values, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_Matrix4x4, rhs: Arvos_Matrix4x4) -> Bool {
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Arvos_CameraIntrinsics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CameraIntrinsics"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fx\0\u{1}fy\0\u{1}cx\0\u{1}cy\0\u{1}distortion\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.fx) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.fy) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.cx) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.cy) }()
      case 5: try { try decoder.decodeRepeatedFloatField(value: &self.distortion) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.fx.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.fx, fieldNumber: 1)
    }
    if self.fy.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.fy, fieldNumber: 2)
    }
    if self.cx.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.cx, fieldNumber: 3)
    }
    if self.cy.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.cy, fieldNumber: 4)
    }
    if !self.distortion.isEmpty {
      try visitor.visitPackedFloatField(value: self.distortion, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Arvos_CameraIntrinsics, rhs: Arvos_CameraIntrinsics) -> Bool {
    if lhs.fx != rhs.fx {return false}
    if lhs.fy != rhs.fy {return false}
    if lhs.cx != rhs.cx {return false}
    if lhs.cy != rhs.cy {return false}
    if lhs.distortion != rhs.distortion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
