// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: sensors.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - arvos.SensorStream

/// Namespace containing generated types for the "arvos.SensorStream" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum Arvos_SensorStream {
    /// Service descriptor for the "arvos.SensorStream" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "arvos.SensorStream")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "StreamSensors" metadata.
        internal enum StreamSensors {
            /// Request type for "StreamSensors".
            internal typealias Input = Arvos_SensorMessage
            /// Response type for "StreamSensors".
            internal typealias Output = Arvos_ControlMessage
            /// Descriptor for "StreamSensors".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "arvos.SensorStream"),
                method: "StreamSensors"
            )
        }
        /// Descriptors for all methods in the "arvos.SensorStream" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            StreamSensors.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "arvos.SensorStream" service.
    internal static let arvos_SensorStream = GRPCCore.ServiceDescriptor(fullyQualifiedService: "arvos.SensorStream")
}

// MARK: arvos.SensorStream (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream {
    /// Streaming variant of the service protocol for the "arvos.SensorStream" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for bidirectional sensor streaming
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "StreamSensors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Arvos_SensorMessage` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Arvos_ControlMessage` messages.
        func streamSensors(
            request: GRPCCore.StreamingServerRequest<Arvos_SensorMessage>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Arvos_ControlMessage>
    }

    /// Service protocol for the "arvos.SensorStream" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for bidirectional sensor streaming
    internal protocol ServiceProtocol: Arvos_SensorStream.StreamingServiceProtocol {
        /// Handle the "StreamSensors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Arvos_SensorMessage` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Arvos_ControlMessage` messages.
        func streamSensors(
            request: GRPCCore.StreamingServerRequest<Arvos_SensorMessage>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Arvos_ControlMessage>
    }

    /// Simple service protocol for the "arvos.SensorStream" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for bidirectional sensor streaming
    internal protocol SimpleServiceProtocol: Arvos_SensorStream.ServiceProtocol {
        /// Handle the "StreamSensors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
        ///
        /// - Parameters:
        ///   - request: A stream of `Arvos_SensorMessage` messages.
        ///   - response: A response stream of `Arvos_ControlMessage` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func streamSensors(
            request: GRPCCore.RPCAsyncSequence<Arvos_SensorMessage, any Swift.Error>,
            response: GRPCCore.RPCWriter<Arvos_ControlMessage>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Arvos_SensorStream.Method.StreamSensors.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Arvos_SensorMessage>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Arvos_ControlMessage>(),
            handler: { request, context in
                try await self.streamSensors(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream.ServiceProtocol {
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream.SimpleServiceProtocol {
    internal func streamSensors(
        request: GRPCCore.StreamingServerRequest<Arvos_SensorMessage>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Arvos_ControlMessage> {
        return GRPCCore.StreamingServerResponse<Arvos_ControlMessage>(
            metadata: [:],
            producer: { writer in
                try await self.streamSensors(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: arvos.SensorStream (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream {
    /// Generated client protocol for the "arvos.SensorStream" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for bidirectional sensor streaming
    internal protocol ClientProtocol: Sendable {
        /// Call the "StreamSensors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Arvos_SensorMessage` messages.
        ///   - serializer: A serializer for `Arvos_SensorMessage` messages.
        ///   - deserializer: A deserializer for `Arvos_ControlMessage` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func streamSensors<Result>(
            request: GRPCCore.StreamingClientRequest<Arvos_SensorMessage>,
            serializer: some GRPCCore.MessageSerializer<Arvos_SensorMessage>,
            deserializer: some GRPCCore.MessageDeserializer<Arvos_ControlMessage>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Arvos_ControlMessage>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "arvos.SensorStream" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for bidirectional sensor streaming
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "StreamSensors" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Arvos_SensorMessage` messages.
        ///   - serializer: A serializer for `Arvos_SensorMessage` messages.
        ///   - deserializer: A deserializer for `Arvos_ControlMessage` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func streamSensors<Result>(
            request: GRPCCore.StreamingClientRequest<Arvos_SensorMessage>,
            serializer: some GRPCCore.MessageSerializer<Arvos_SensorMessage>,
            deserializer: some GRPCCore.MessageDeserializer<Arvos_ControlMessage>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Arvos_ControlMessage>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: Arvos_SensorStream.Method.StreamSensors.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream.ClientProtocol {
    /// Call the "StreamSensors" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Arvos_SensorMessage` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func streamSensors<Result>(
        request: GRPCCore.StreamingClientRequest<Arvos_SensorMessage>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Arvos_ControlMessage>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.streamSensors(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Arvos_SensorMessage>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Arvos_ControlMessage>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Arvos_SensorStream.ClientProtocol {
    /// Call the "StreamSensors" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Bidirectional streaming - iPhone sends sensor data, server can send control commands
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func streamSensors<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Arvos_SensorMessage>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Arvos_ControlMessage>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Arvos_SensorMessage>(
            metadata: metadata,
            producer: producer
        )
        return try await self.streamSensors(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}